### ISSUE TITLE
Can not complete scan

### ISSUE THREAD

**Issue by Pharaoh2k** [avan06/PS4CheaterNeo#22]
Hi, Avan, just tested the latest 0.9.9.1 beta and noticed the first scan was stuck at the end.
![WGwcpyr](https://github.com/avan06/PS4CheaterNeo/assets/5753365/49d90c4f-bfaa-4ab4-9527-e1a3d45730d4)

When I hit the stop button, I got this error:
```
System.AggregateException: One or more errors occurred. ---> System.Exception: System.Exception: baseKey must be less than key, baseKey:4904657, key:16
   at PS4CheaterNeo.BitsDictionary.Add(UInt32 key, Byte[] data)
   at PS4CheaterNeo.Query.Comparer(Byte[] buffer, Section section, Int32 scanStep, UInt64 AddrMin, UInt64 AddrMax, BitsDictionary bitsDict)
   at PS4CheaterNeo.Query.<>c__DisplayClass30_3.<ScanTask>b__5()

System.AggregateException: One or more errors occurred. ---> System.Exception: baseKey must be less than key, baseKey:4904657, key:16
   at PS4CheaterNeo.Query.<>c__DisplayClass30_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PS4CheaterNeo.Query.<>c__DisplayClass30_0.<ScanTask>b__0()
---> (Inner Exception #0) System.Exception: baseKey must be less than key, baseKey:4904657, key:16
   at PS4CheaterNeo.Query.<>c__DisplayClass30_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---



   at PS4CheaterNeo.Query.<>c__DisplayClass30_0.<ScanTask>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PS4CheaterNeo.Query.<ScanTask>d__30.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: System.Exception: baseKey must be less than key, baseKey:4904657, key:16
   at PS4CheaterNeo.BitsDictionary.Add(UInt32 key, Byte[] data)
   at PS4CheaterNeo.Query.Comparer(Byte[] buffer, Section section, Int32 scanStep, UInt64 AddrMin, UInt64 AddrMax, BitsDictionary bitsDict)
   at PS4CheaterNeo.Query.<>c__DisplayClass30_3.<ScanTask>b__5()

System.AggregateException: One or more errors occurred. ---> System.Exception: baseKey must be less than key, baseKey:4904657, key:16
   at PS4CheaterNeo.Query.<>c__DisplayClass30_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PS4CheaterNeo.Query.<>c__DisplayClass30_0.<ScanTask>b__0()
---> (Inner Exception #0) System.Exception: baseKey must be less than key, baseKey:4904657, key:16
   at PS4CheaterNeo.Query.<>c__DisplayClass30_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---



   at PS4CheaterNeo.Query.<>c__DisplayClass30_0.<ScanTask>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PS4CheaterNeo.Query.<ScanTask>d__30.MoveNext()<---
```

**Comment by avan06** [comment]
Hi, Pharaoh2k,
Thank you for bringing up the issue with the ScanTask stop button. 
This issue has been fixed in version [0.9.9.2-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.2-beta). Thank you.

**Comment by Pharaoh2k** [comment]
I still get no results.
To reproduce:
- Connect to cyberpunk
- Select the second exec section at address 0500000 (prot 1).
- Select Byte
- Select UnknownInitial
- Scan

These are my exact settings:
![hIY7Pmm](https://github.com/avan06/PS4CheaterNeo/assets/5753365/bbf72644-20f2-49bb-a306-49151db68859)

**Comment by Pharaoh2k** [comment]
by the way. Since the scan obviously finished, but not showing any results in the list, I tried to click the stop button and getting this:
![4fnYWHs](https://github.com/avan06/PS4CheaterNeo/assets/5753365/7e4c10c2-4f8a-430d-8cef-f1782fec09d5)

**Comment by avan06** [comment]
> I still get no results. To reproduce:
> 
> * Connect to cyberpunk
> * Select the second exec section at address 0500000 (prot 1).
> * Select Byte
> * Select UnknownInitial
> * Scan
Hi, Pharaoh2k,

After using version 0.9.9.2-beta or a newer version, do you still encounter an error message when the program is stuck on this screen? Does the game that's set to auto-pause automatically resume? It seems that the scan hasn't completed yet (or there might be an issue causing it to get stuck and not complete).

I conducted the same scanning test with Cyberpunk 2077, and the results were normal. However, I haven't played this game, so I performed the scan in the game's initial prologue at the car workshop.

**Comment by Pharaoh2k** [comment]
No, avan, I don't get the error message anymore, but the scan never completes when I do the steps I mentioned.
I am attaching my exported config. Maybe you can try to use my config and see if you can reproduce this issue.
[PS4CheaterNeoConfig.zip](https://github.com/avan06/PS4CheaterNeo/files/12565482/PS4CheaterNeoConfig.zip)

**Comment by Pharaoh2k** [comment]
Sorry, this is the correct json file:
[PS4CheaterNeoSettings.zip](https://github.com/avan06/PS4CheaterNeo/files/12565499/PS4CheaterNeoSettings.zip)

**Comment by Pharaoh2k** [comment]
I think I found the cause. I have set the "Max results show" to 1 million results instead of the default 8,192.
Neo seems to have a hard time listing a long list of results. Even the 8,192 listing isn't instant.
Could you please look into improving the performance of the result listing speed? 
I know that on cheater it lists a small or large list of results almost instantly. I have a test build (1.5.4.8) that can actually list up to 1 million results almost instantly.

**Comment by Pharaoh2k** [comment]
by the way, please check your discord, I have sent some more info there.

**Comment by avan06** [comment]
> I think I found the cause. I have set the "Max results show" to 1 million results instead of the default 8,192. Neo seems to have a hard time listing a long list of results. Even the 8,192 listing isn't instant. 
Haha! I didn't expect anyone to set it to a million results here. I can try to improve this part. Thanks, Pharaoh2k, for helping identify the issue!

**Comment by avan06** [comment]
The efficiency issue in ResultView has been resolved in version [0.9.9.4-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.4-beta). Additionally, improvements have been made to the efficiency of SectionView. However, further testing is needed to ensure everything works well due to significant program changes. Thank you.

**Comment by Pharaoh2k** [comment]
Indeed the performance is A LOT better than it has ever been! Well done!
I will keep this issue open for now just in case I find any related issues to report here.

**Comment by Pharaoh2k** [comment]
Closing this for now. Thanks a lot! :)
